apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - source-statefulset.yml
  - source-pvc.yml

configMapGenerator:
  - name: postgres-init
    files:
      - sql/01_init.sql
      - sql/02_seed.sql