transformation:
  target: dev


  outputs:
    dev:
      type: trino
      method: none
      user: trino
      password: ""
      host: localhost
      port: 8080
      database: iceberg
      schema: "ecom"

      threads: 4

