apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-etl-config
  namespace: airflow
data:
  POSTGRES_DB: "ecom_db"
  POSTGRES_PORT: "5432"

  NESSIE_URI: "http://nessie:19120"
  ICEBERG_WAREHOUSE: "s3://ecom-etl/warehouse"

  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: "ecom-etl"
  MINIO_REGION: "us-east-1"

  SEMANTIC_LAYER_URL: "http://semantic-layer:8001"