# ─────────────────────────────────────
# EXECUTOR
# ─────────────────────────────────────
executor: LocalExecutor

# ─────────────────────────────────────
# CUSTOM IMAGE — etl_ecom installed
# ─────────────────────────────────────
images:
  airflow:
    repository: ghcr.io/cdjepeno/ecom-airflow
    tag: latest
    pullPolicy: Always


# ─────────────────────────────────────
# DATABASE MIGRATION JOB
# ─────────────────────────────────────
migrateDatabaseJob:
  enabled: true  

# ─────────────────────────────────────
# DAGs — gitSync from GitHub
# ─────────────────────────────────────
dags:
  gitSync:
    enabled: true
    repo: https://github.com/CDjepeno/ai-data-platform-ecom.git
    branch: pre-prod
    subPath: src/airflow/dags
    period: 60s

# ─────────────────────────────────────
# WEBSERVER
# ─────────────────────────────────────
createUserJob:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: djepenodev@gmail.com
    password: admin

# ─────────────────────────────────────
# METADATA DB — bundled PostgreSQL
# ─────────────────────────────────────
postgresql:
  enabled: false

# ─────────────────────────────────────
# MISC
# ─────────────────────────────────────
config:
  core:
    load_examples: "False"


data:
  metadataSecretName: airflow-postgres-secret
  resultBackendSecretName: airflow-postgres-secret

fernetKeySecretName: airflow-fernet-key

extraEnvFrom: |
  - secretRef:
      name: airflow-airbyte-secret
  - secretRef:
      name: airflow-etl-secret
  - configMapRef:
      name: airflow-etl-config
   - configMapRef:
      name: etl-config
  
  
