name: ecom-data-platform-dev

services:

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
    # host:container -> 5434 (host) to 5432 (postgres container)
      - "5434:5432"
    volumes:
        - postgres_data_dev:/var/lib/postgresql/data
        - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etl_ecom
    
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"     
      - "9001:9001"     
    env_file:
      - .env         
    volumes:
      - minio_data_dev:/data
    command: server /data --console-address ":9001"
    networks:
      - etl_ecom

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie

    ports:
      - "19120:19120"

    environment:
      - QUARKUS_HTTP_PORT=19120

      # =========================
      # ICEBERG REST
      # =========================

      - nessie.catalog.default-warehouse=warehouse

      - nessie.catalog.warehouses.warehouse.location=s3://ecom-etl/warehouse

      # =========================
      # MINIO
      # =========================

      - nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.service.s3.default-options.region=us-east-1

      # 🔥 IMPORTANT
      - nessie.catalog.service.s3.default-options.auth-type=application-global

      # GLOBAL AWS CREDS
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=us-east-1
      - nessie.version.store.type=ROCKSDB
      - nessie.version.store.persist.directory=/nessie-data   
    volumes:
      - nessie_data:/nessie-data
    networks:
      - etl_ecom

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - minio
      - nessie
    networks:
      - etl_ecom
  
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant

    ports:
      - "6334:6333"

    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - etl_ecom

  pipeline:
    build: 
      context: ../src/etl_ecom
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      semantic_layer:
        condition: service_healthy    
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - etl_ecom
    volumes:
      - ../src/etl_ecom:/app
      - ../src/semantic_layer:/app/semantic_layer

  api:
    build:
      context: ../src/fast_api

    ports:
      - "8000:8000"

    working_dir: /app

    env_file:
      - .env

    volumes:
    - ../src/fast_api:/app/fast_api

    depends_on:
      - semantic_layer

    networks:
      - etl_ecom
    
  semantic_layer:
    build:
      context: ../src/semantic_layer
      args:
        HF_TOKEN: ${HF_TOKEN}
    working_dir: /app
    ports:
    - "8001:8001"
    env_file:
      - .env
    volumes:
      - ../src/semantic_layer:/app
      - ../src/etl_ecom:/app/etl_ecom
      - ../src/semantic_layer/.dbt:/app/.dbt

    depends_on:
      - trino
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s 

    networks:
      - etl_ecom

  # frontend:
  #   build:
  #     context: ../src/next_js

  #   container_name: next_frontend

  #   ports:
  #     - "3000:3000"

  #   volumes:
  #     - ../src/next_js:/app
  #     - /app/node_modules

  #   depends_on:
  #     - api

  #   networks:
  #     - etl_ecom

   # ==============================
  # MONITORING
  # ==============================

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    depends_on:
      - api
      - semantic_layer
    networks:
      - etl_ecom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - etl_ecom

  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"
    networks:
      - etl_ecom
    volumes:
      - valkey_data:/data
    command: valkey-server --save 60 1 --loglevel warning

volumes:
  minio_data_dev: 
  postgres_data_dev:
  qdrant_data:
  nessie_data:
  prometheus_data:
  grafana_data:
  valkey_data:

networks:
  etl_ecom: