apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
secretGenerator:
  - name: postgres-secret
    envs:
      - ../../env-local/.env.etl
    options:
      disableNameSuffixHash: true
  - name: minio-secret
    envs:
      - ../../env-local/.env.minio
    options:
      disableNameSuffixHash: true