apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecom-preprod

resources:
  - namespace.yml
  - configmap-env.yml
  - ../../../base/minio/
  - ../../../base/valkey/
  - ../../../base/qdrant/
  - ../../../base/nessie/
  - ../../../base/trino/
  - trino-configmap.yml
  - trino-server-configmap.yml
  - http-route-minio.yaml
  - http-route-qdrant.yaml
  - http-route-trino.yaml
  - http-route-next.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: trino
      spec:
        template:
          spec:
            containers:
              - name: trino
                volumeMounts:
                  - name: trino-server-config
                    mountPath: /etc/trino/config.properties
                    subPath: config.properties
            volumes:
              - name: trino-server-config
                configMap:
                  name: trino-server-config
    target:
      kind: Deployment
      name: trino

