apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecom-dev

resources:
  - namespace.yml
  - configmap-env.yml
  - ../../base/valkey/
  - ../../base/qdrant/
  - ../../base/nessie/
  - ../../base/trino/
