apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trino-configmap.yml
  - trino-server-configmap.yml

  - http-route-minio.yaml
  - http-route-qdrant.yaml
  - http-route-trino.yaml
  - configmap-etl.yaml
