apiVersion: v1
kind: Secret

metadata:
  name: warehouse-s3-secret
  namespace: ecom-pre-prod

  labels:
    app: trino
    component: sql-engine

type: Opaque

stringData:
  access_key: YOUR_OVH_S3_ACCESS_KEY
  secret_key: YOUR_OVH_S3_SECRET_KEY