apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - manifests/namespace-networking.yaml
  - manifests/http-route-nginx.yaml
  - manifests/http-route-grafana.yaml
  - manifests/http-route-prometheus.yaml

  - otel-collector
  - tempo


