# ─────────────────────────────────────
# EXECUTOR
# ─────────────────────────────────────
executor: LocalExecutor

# ─────────────────────────────────────
# CUSTOM IMAGE — etl_ecom installed
# ─────────────────────────────────────
images:
  airflow:
    repository: airflow-ecom
    tag: local
    pullPolicy: Never

# ─────────────────────────────────────
# DATABASE MIGRATION JOB
# ─────────────────────────────────────
migrateDatabaseJob:
  enabled: true  

# ─────────────────────────────────────
# DAGs — gitSync from GitHub
# ─────────────────────────────────────
dags:
  gitSync:
    enabled: true
    repo: https://github.com/CDjepeno/ecom-data_platform.git
    branch: main
    subPath: src/airflow/dags
    period: 60s
    credentialsSecret: airflow-git-secret

# ─────────────────────────────────────
# WEBSERVER
# ─────────────────────────────────────
createUserJob:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: djepenodev@gmail.com
    password: admin

# ─────────────────────────────────────
# METADATA DB — bundled PostgreSQL
# ─────────────────────────────────────
postgresql:
  enabled: true

# ─────────────────────────────────────
# MISC
# ─────────────────────────────────────
config:
  core:
    load_examples: "False"
