apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nessie
  labels:
    app: nessie
    component: iceberg-catalog
spec:
  serviceName: nessie
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
        component: iceberg-catalog
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.107.5
          ports:
            - containerPort: 19120
              name: http

          envFrom:
            - configMapRef:
                name: ecom-config   

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_SECRET_ACCESS_KEY

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: nessie-data
              mountPath: /nessie-data
          readinessProbe:
            tcpSocket:
              port: 19120
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 19120
            initialDelaySeconds: 60
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: nessie-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
