# ─────────────────────────────────────
# EXECUTOR
# ─────────────────────────────────────
executor: LocalExecutor

# ─────────────────────────────────────
# CUSTOM IMAGE — etl_ecom installed
# ─────────────────────────────────────
images:
  airflow:
    repository: airflow-ecom
    tag: local
    pullPolicy: Never

# ─────────────────────────────────────
# DAGs — gitSync from GitHub
# ─────────────────────────────────────
dags:
  gitSync:
    enabled: true
    repo: https://github.com/CDjepeno/ecom-data-platform.git
    branch: feat/add-airbyte-and-marketing-source
    subPath: src/airflow/dags
    period: 60s
    recommendedProbeSetting: true
    credentialsSecret: airflow-git-secret 

# ─────────────────────────────────────
# WEBSERVER
# ─────────────────────────────────────
createUserJob:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: djepenodev@gmail.com
    password: admin

# ─────────────────────────────────────
# METADATA DB — bundled PostgreSQL
# ─────────────────────────────────────
postgresql:
  enabled: true

# ─────────────────────────────────────
# MISC
# ─────────────────────────────────────
config:
  core:
    load_examples: "False"

# ─────────────────────────────────────
# SCHEDULER
# ─────────────────────────────────────
scheduler:
  waitForMigrations:
    enabled: true
    env:
      - name: AIRFLOW__DATABASE__MIGRATION_WAIT_TIMEOUT
        value: "300"  # increase from 60s to 300s

# ─────────────────────────────────────
# TRIGGERER  
# ─────────────────────────────────────
triggerer:
  waitForMigrations:
    enabled: true
    env:
      - name: AIRFLOW__DATABASE__MIGRATION_WAIT_TIMEOUT
        value: "300"

# ─────────────────────────────────────
# GLOBAL ENV
# ─────────────────────────────────────
env:
  - name: AIRFLOW__DATABASE__MIGRATION_WAIT_TIMEOUT
    value: "300"
