kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    # Map host ports so ingress-nginx NodePort is reachable from your browser
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 5434       
        hostPort: 5434
        protocol: TCP
      - containerPort: 9000      
        hostPort: 9000
        protocol: TCP
      - containerPort: 9001      # 
        hostPort: 9001
        protocol: TCP
    # Patch ingress-nginx to bind to this node via label
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /home/djepeno/sites/ai-data-platform-ecom/src/airflow/dags
        containerPath: /dags

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=data"
    extraMounts:
      - hostPath: /home/djepeno/sites/ai-data-platform-ecom/src/airflow/dags
        containerPath: /dags

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=app"
    extraMounts:
      - hostPath: /home/djepeno/sites/ai-data-platform-ecom/src/airflow/dags
        containerPath: /dags